import hashlib

import bcrypt

_PREFIX = "bcrypt_sha256$"


def _sha256_bytes(password: str) -> bytes:
    # Pre-hash to avoid bcrypt's 72-byte input limit while keeping consistent behavior.
    return hashlib.sha256(password.encode("utf-8")).hexdigest().encode("utf-8")


def hash_password(password: str) -> str:
    hashed = bcrypt.hashpw(_sha256_bytes(password), bcrypt.gensalt())
    return f"{_PREFIX}{hashed.decode('utf-8')}"


def verify_password(plain: str, hashed: str) -> bool:
    # New format generated by this service.
    if hashed.startswith(_PREFIX):
        real_hash = hashed[len(_PREFIX):].encode("utf-8")
        return bcrypt.checkpw(_sha256_bytes(plain), real_hash)

    # Backward compatibility with existing raw bcrypt hashes.
    try:
        return bcrypt.checkpw(plain.encode("utf-8"), hashed.encode("utf-8"))
    except ValueError:
        return False